### ISSUE TITLE
Remove magic numbers for maximum body size

### ISSUE THREAD

**Issue by bcongdon** [arbor-dev/arbor#49]
See https://github.com/arbor-dev/arbor/blob/master/proxy/PUT.go#L53

Would be good to define a `MB` constant, and make these `n * MB` limits, instead of having a magic number.

Also, we're inconsistent here. For example, we don't enforce a limit for `GET` requests

**Comment by theishshah** [comment]
This looks done in PR #48 ...ready to close the issue?

**Comment by bcongdon** [comment]
Yup, thanks for the ping.
